/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/com/qualcomm/qti/location/LocationSomeIPDeployment.hpp>

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace location {
namespace Location_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments
CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::location::LocationTypes_::LocationReportTDeployment_t > GnssEngineLocationsReport_locationReportDeployment(&::v1::com::qualcomm::qti::location::LocationTypes_::LocationReportTDeployment, 0, 0, 4);
CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSvDataTDeployment_t > GnssSvReport_gnssSvDeployment(&::v1::com::qualcomm::qti::location::LocationTypes_::GnssSvDataTDeployment, 0, 0, 4);

} // namespace Location_
} // namespace location
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1
