/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_COM_QUALCOMM_QTI_LOCATION_LOCATION_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define V1_COM_QUALCOMM_QTI_LOCATION_LOCATION_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace qualcomm {
namespace qti {
namespace location {
namespace LocationTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> MapMatchingFeedbackDataValidityTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssReportCbInfoMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationStatusTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocReqEngineTypeMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> EngineReportCbMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> AidingDataDeletionMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssConstellationTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationCapabilitiesMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssMeasurementsClockFlagsMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssMeasurementsDataFlagsMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssSvTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssMeasurementsStateMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssMeasurementsAdrStateMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssMeasurementsMultipathIndicatorTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssSignalTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssMeasCodeTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationFlagsMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationTechnologyMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationReportFlagMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationReliabilityTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationReportNavSolutionMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationReportPosDataMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssLocSvSystemTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssSystemTimeStructTypeFlagsTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssGloTimeStructTypeFlagsTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DrCalibrationStatusMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocOutputEngineTypeTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> PositioningEngineMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DrSolutionStatusMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocationReportExtendedFlagMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> LocSessionStatusTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssSvOptionsMaskTDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GnssDataMaskTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> MapMatchingFeedbackDataTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssConstellationTypeTDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> GnssSvIdInfoTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>
> GnssMeasurementsClockTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSvTypeTDeployment_t,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSignalTypeTDeployment_t,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasCodeTypeTDeployment_t,
    CommonAPI::SomeIP::StringDeployment
> GnssMeasurementsDataTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<int32_t>,
        CommonAPI::SomeIP::IntegerDeployment<int64_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::SomeIP::IntegerDeployment<int64_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>
    >,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::SomeIP::StructDeployment<
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSvTypeTDeployment_t,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<int64_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<int64_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<int64_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSignalTypeTDeployment_t,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasCodeTypeTDeployment_t,
            CommonAPI::SomeIP::StringDeployment
        >
    >,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>
> GnssMeasurementsTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::EmptyDeployment
> LocationTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>
> LocationReportSvUsedInPositionTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> LocationReportPositionDynamicsTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> GnssSystemTimeStructTypeTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> GnssGloTimeStructTypeTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    >,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    >
> SystemTimeStructTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssLocSvSystemTypeTDeployment_t,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::StructDeployment<
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>
        >,
        CommonAPI::SomeIP::StructDeployment<
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::EmptyDeployment,
            CommonAPI::EmptyDeployment,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>
        >
    >
> GnssSystemTimeTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssConstellationTypeTDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSignalTypeTDeployment_t
> GnssMeasUsageInfoTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> LlaInfoTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint64_t>
    >,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::SomeIP::StructDeployment<
        ::v1::com::qualcomm::qti::location::LocationTypes_::GnssLocSvSystemTypeTDeployment_t,
        CommonAPI::SomeIP::StructDeployment<
            CommonAPI::SomeIP::StructDeployment<
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::EmptyDeployment,
                CommonAPI::EmptyDeployment,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >,
            CommonAPI::SomeIP::StructDeployment<
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::EmptyDeployment,
                CommonAPI::EmptyDeployment,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >
    >,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::SomeIP::StructDeployment<
            ::v1::com::qualcomm::qti::location::LocationTypes_::GnssConstellationTypeTDeployment_t,
            CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
            ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSignalTypeTDeployment_t
        >
    >,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    ::v1::com::qualcomm::qti::location::LocationTypes_::LocOutputEngineTypeTDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    ::v1::com::qualcomm::qti::location::LocationTypes_::LocSessionStatusTDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    >,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint64_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<int32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> LocationReportTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSvTypeTDeployment_t,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::EmptyDeployment,
    ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSignalTypeTDeployment_t,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>
> GnssSvDataTDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    >,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::EmptyDeployment
    >,
    CommonAPI::SomeIP::ArrayDeployment<
        CommonAPI::EmptyDeployment
    >
> GnssDataTDeployment_t;


// typecollection-specific deployments
COMMONAPI_EXPORT extern MapMatchingFeedbackDataValidityTDeployment_t MapMatchingFeedbackDataValidityTDeployment;
COMMONAPI_EXPORT extern GnssReportCbInfoMaskTDeployment_t GnssReportCbInfoMaskTDeployment;
COMMONAPI_EXPORT extern LocReqEngineTypeMaskTDeployment_t LocReqEngineTypeMaskTDeployment;
COMMONAPI_EXPORT extern EngineReportCbMaskTDeployment_t EngineReportCbMaskTDeployment;
COMMONAPI_EXPORT extern AidingDataDeletionMaskTDeployment_t AidingDataDeletionMaskTDeployment;
COMMONAPI_EXPORT extern LocationCapabilitiesMaskTDeployment_t LocationCapabilitiesMaskTDeployment;
COMMONAPI_EXPORT extern GnssMeasurementsClockFlagsMaskTDeployment_t GnssMeasurementsClockFlagsMaskTDeployment;
COMMONAPI_EXPORT extern GnssMeasurementsDataFlagsMaskTDeployment_t GnssMeasurementsDataFlagsMaskTDeployment;
COMMONAPI_EXPORT extern GnssMeasurementsStateMaskTDeployment_t GnssMeasurementsStateMaskTDeployment;
COMMONAPI_EXPORT extern GnssMeasurementsAdrStateMaskTDeployment_t GnssMeasurementsAdrStateMaskTDeployment;
COMMONAPI_EXPORT extern GnssMeasurementsMultipathIndicatorTDeployment_t GnssMeasurementsMultipathIndicatorTDeployment;
COMMONAPI_EXPORT extern GnssSignalTypeTDeployment_t GnssSignalTypeTDeployment;
COMMONAPI_EXPORT extern LocationFlagsMaskTDeployment_t LocationFlagsMaskTDeployment;
COMMONAPI_EXPORT extern LocationTechnologyMaskTDeployment_t LocationTechnologyMaskTDeployment;
COMMONAPI_EXPORT extern LocationReportFlagMaskTDeployment_t LocationReportFlagMaskTDeployment;
COMMONAPI_EXPORT extern LocationReportNavSolutionMaskTDeployment_t LocationReportNavSolutionMaskTDeployment;
COMMONAPI_EXPORT extern LocationReportPosDataMaskTDeployment_t LocationReportPosDataMaskTDeployment;
COMMONAPI_EXPORT extern GnssSystemTimeStructTypeFlagsTDeployment_t GnssSystemTimeStructTypeFlagsTDeployment;
COMMONAPI_EXPORT extern GnssGloTimeStructTypeFlagsTDeployment_t GnssGloTimeStructTypeFlagsTDeployment;
COMMONAPI_EXPORT extern DrCalibrationStatusMaskTDeployment_t DrCalibrationStatusMaskTDeployment;
COMMONAPI_EXPORT extern PositioningEngineMaskTDeployment_t PositioningEngineMaskTDeployment;
COMMONAPI_EXPORT extern DrSolutionStatusMaskTDeployment_t DrSolutionStatusMaskTDeployment;
COMMONAPI_EXPORT extern LocationReportExtendedFlagMaskTDeployment_t LocationReportExtendedFlagMaskTDeployment;
COMMONAPI_EXPORT extern GnssSvOptionsMaskTDeployment_t GnssSvOptionsMaskTDeployment;
COMMONAPI_EXPORT extern GnssDataMaskTDeployment_t GnssDataMaskTDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasurementsDataTDeployment_t GnssMeasurementsDataTDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasurementsDataTDeployment_t > GnssMeasurementsT_measurementsDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasurementsTDeployment_t GnssMeasurementsTDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasUsageInfoTDeployment_t GnssMeasUsageInfoTDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::com::qualcomm::qti::location::LocationTypes_::GnssMeasUsageInfoTDeployment_t > LocationReportT_measUsageInfoDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::location::LocationTypes_::LocationReportTDeployment_t LocationReportTDeployment;
COMMONAPI_EXPORT extern ::v1::com::qualcomm::qti::location::LocationTypes_::GnssSvDataTDeployment_t GnssSvDataTDeployment;

} // namespace LocationTypes_
} // namespace location
} // namespace qti
} // namespace qualcomm
} // namespace com
} // namespace v1

#endif // V1_COM_QUALCOMM_QTI_LOCATION_LOCATION_TYPES_SOMEIP_DEPLOYMENT_HPP_
